Batch/urls.py
from django.urls import path
from .admin import prosperity_admin_site
from . import views

app_name = 'batch'

urlpatterns = [
    # post views
    path('',views.all_batches, name='batches'),
    path('drafts/',views.draft_batches, name='drafts'),
    path('codes/', views.get_deduction_codes, name='codes'),
    path('codes/new/',views.deduction_code_registration, name='code_registration'),
    path('send/batch/',views.send_batch, name='send_batch'),
    path('<int:id>/upload_excel/', views.upload_responses, name='upload_excel'),
    path('<int:id>/',views.view_batch, name='view_batch'),
]

Company/urls.py
from django.urls import path
from . import views

app_name = 'company'

urlpatterns = [
    # post views
    path('',views.get_companies, name='companies'),
    path('registration/', views.company_registration, name='company_registration'),
    path('dashboard/', views.company_dashboard, name='dashboard'),
]

ProsperityPartners/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Accounts.urls',namespace='accounts')),
    path('batches/', include('Batch.urls', namespace='batch')),
    path('companies/', include('Company.urls', namespace='company')),
    path('records/', include('Record.urls', namespace='record')),
    path('responses/', include('Response.urls', namespace='response')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
#django-insecure-m0s&i_6&kcp39hv53*g$=64e6#ppb&efdxm!krv!l7_#q%w&a$

Company/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import Group
import uuid
# Create your models here.


class Company(models.Model):
    class Status(models.TextChoices):
        ACTIVE = 'ACTIVE','ACTIVE'
        SUSPENDED = 'SUSPENDED','SUSPENDED'
        DEACTIVATED = 'DEACTIVATED','DEACTIVATED'
    
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    company_ceo = models.CharField(max_length=100)
    physical_address = models.CharField(max_length=100)
    postal_address = models.CharField(max_length=100)
    town = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    email_address = models.EmailField(max_length=100)
    date_joined = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=100,choices = Status.choices,default=Status.ACTIVE)
    
    def __str__(self): return self.name
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'
        
        
    def save(self, *args, **kwargs):
        Group.objects.get_or_create(name =self.name)
        super(Company, self).save(*args, **kwargs)
  

Company/forms.py
from django import forms
import re

from Company.models import Company

#Applicant Form 1
class CompanyForm(forms.ModelForm):
    name = forms.CharField(max_length=250)
    class Meta:
        model = Company
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})

Company/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group

from Company.models import Company
from Company.forms import CompanyForm

def company_registration(request):
    if request.method =='POST':
        form = CompanyForm(request.POST)
        if form.is_valid():
            company = form.save()
            Group.objects.create(name = company.name)
            return redirect("company:companies")
    else:
        form = CompanyForm()
    return render(request,'company/add-company.html',{'form':form})


@login_required
def get_companies(request):
    companies = Company.objects.all()
    return render(request,'company/companies.html',{'companies':companies})

@login_required
def company_dashboard(request):
    return render(request,'dashboard/dashboard.html')

templates/company/add-company.html
{% extends '../dashboard/base.html' %}
{% block body %}
<div class="page-header1">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-7">
                <div class="page-header-title">
                    <h5 class="m-b-10 m-t-4 m-l-4">Company Management</h5>
                    <p class="m-b-0"></p>
                </div>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb">
                    {% comment %} <li class="breadcrumb-item">
                        <a href="index.html"> <i class="fa fa-home"></i> </a>
                    </li> {% endcomment %}
                    <li class="breadcrumb-item">
                        <button class="btn waves-effect waves-light btn-primary"><i class="icofont icofont-user-alt-3"></i>New Record</button>
                    </li>
                    <li class="breadcrumb-item">
                        <button class="btn waves-effect waves-light btn-success"><i class="icofont icofont-check-circled"></i>Import Bulk Records</button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Page-header end -->
<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">

            <!-- Page body start -->
            <div class="page-body">
                <div class="row">
                    {% comment %} <div class="col-md-1"></div> {% endcomment %}
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Add New Company</h5>
                            </div>
                            <div class="card-block">
                                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                                    <div class="form-group row">
                                        <div class="col-lg-3"></div>
                                        <div class="col-lg-6">
                                            <label class="float-label">Enter Company Name <span style="color:red;">*</span></label>
                                            {{form.name}}
                                        </div>
                                    </div>
                                    <div style="text-align:center;">
                                        <button type="submit" class="btn btn-primary waves-effect waves-light">Add Company</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% comment %} <div class="col-md-1"></div> {% endcomment %}
                </div>
            </div>
            <!-- Page body end -->
        </div>
    </div>
    <!-- Main-body end -->
</div>
{% endblock body %}

templates/company/companies.html
{% extends '../dashboard/base.html' %}
{% load static %}

{% block body %}
<div class="page-header1">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-9">
                <div class="page-header-title">
                    <h5 class="m-b-10 m-t-4 m-l-4">Company Management</h5>
                    <p class="m-b-0"></p>
                </div>
            </div>
            <div class="col-md-3">
                <ul class="breadcrumb">
                    {% comment %} <li class="breadcrumb-item">
                        <a href="index.html"> <i class="fa fa-home"></i> </a>
                    </li> {% endcomment %}
                    <li class="breadcrumb-item">
                        <a href="{% url 'company:company_registration' %}" class="btn waves-effect waves-light btn-success"><i class="icofont icofont-check-circled"></i>Add New Company</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Page-header end -->
<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Hover table card start -->
            <div class="card">
                <div class="card-header">
                    <h5>Companies</h5>
                    <div class="card-header-right">
                        <ul class="list-unstyled card-option">
                            <li><i class="fa fa fa-wrench open-card-option"></i></li>
                            <li><i class="fa fa-window-maximize full-card"></i></li>
                            <li><i class="fa fa-minus minimize-card"></i></li>
                            <li><i class="fa fa-refresh reload-card"></i></li>
                            <li><i class="fa fa-trash close-card"></i></li>
                        </ul>
                    </div>
                </div>
                <div class="card-block table-border-style">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr style="background-color:#5A72FE;">
                                    <th></th>
                                    <th style="color:white;">Company</th>
                                    <th style="color:white;">Date Registered</th>
                                    <th style="color:white;">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for company in companies %}
                                    <tr>
                                        <th scope="row">{{forloop.counter}}</th>
                                        <td>{{company.name}}</td>
                                        <td>{{company.date_created}}</td>
                                        <td><label class="label label-success">Active</label></td>
                                    </tr>
                                {% empty %}
                                    <p>No company registered yet.</p>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Hover table card end -->
        </div>
        <!-- Page body end -->
    </div>
</div>
<!-- Main-body end -->

{% endblock body %}

templates/company/invoice.html
{% extends '../dashboard/base.html' %}
{% block body %}
{% comment %} <div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h5 class="m-b-10">Invoice</h5>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="#!">Invoice</a></li>
                </ul>
            </div>
        </div>
    </div>
</div> {% endcomment %}

<div class="row">

<div class="container" id="printTable">
    <div>
        <div class="card">
        <div class="row invoice-contact">
            <div class="col-md-8">
                <div class="invoice-box row">
                    <div class="col-sm-12">
                        <table class="table table-responsive invoice-table table-borderless p-l-20">
                            <tbody>
                                <tr>
                                    <td><a href="index.html" class="b-brand">
                                        <img class="img-fluid" src="../assets/images/logo-dark.svg" alt="flash Able Logo">
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Company name </td>
                                </tr>
                                <tr>
                                    <td>1065 Mandan Road, Columbia MO, Missouri. (123)-65202</td>
                                </tr>
                                <tr>
                                    <td><a class="text-secondary" href="/cdn-cgi/l/email-protection#385c5d5557785f55595154165b5755" target="_top"><span class="__cf_email__" data-cfemail="2347464e4c63444e424a4f0d404c4e">[email&#160;protected]</span></a></td>
                                </tr>
                                <tr>
                                    <td>+91 919-91-91-919</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
            </div>
            <div class="card-body">
                <div class="row invoive-info">
                    <div class="col-md-4 col-xs-12 invoice-client-info">
                        <h6>Client Information :</h6>
                        <h6 class="m-0">Josephin Villa</h6>
                        <p class="m-0 m-t-10">1065 Mandan Road, Columbia MO, Missouri. (123)-65202</p>
                        <p class="m-0">(1234) - 567891</p>
                        <p><a class="text-secondary" href="/cdn-cgi/l/email-protection#9ffbfaf2f0dff8f2fef6f3b1fcf0f2" target="_top"><span class="__cf_email__" data-cfemail="f59190989ab59298949c99db969a98">[email&#160;protected]</span></a></p>
                    </div>
                    <div class="col-md-4 col-sm-6">
                        <h6>Order Information :</h6>
                        <table class="table table-responsive invoice-table invoice-order table-borderless">
                            <tbody>
                                <tr>
                                    <th>Date :</th>
                                    <td>November 14</td>
                                    </tr>
                                <tr>
                                    <th>Status :</th>
                                    <td>
                                        <span class="label label-warning">Pending</span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Id :</th>
                                <td>
                                #146859
                                </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-4 col-sm-6">
                        <h6 class="m-b-20">Invoice Number <span>#125863478945</span></h6>
                        <h6 class="text-uppercase text-primary">Total Due :
                        <span>$950.00</span>
                        </h6>
                    </div>
                </div>
                <div class="row">
                <div class="col-sm-12">
                    <div class="table-responsive">
                    <table class="table invoice-detail-table">
                        <thead>
                            <tr class="thead-default">
                                <th>Description</th>
                                <th>Quantity</th>
                                <th>Amount</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <h6>Logo Design</h6>
                                    <p class="m-0">lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
                                </td>
                                <td>6</td>
                                <td>$200.00</td>
                                <td>$1200.00</td>
                            </tr>
                            <tr>
                                <td>
                                    <h6>Logo Design</h6>
                                    <p class="m-0">lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
                                </td>
                                <td>7</td>
                                <td>$100.00</td>
                                <td>$700.00</td>
                            </tr>
                            <tr>
                                <td>
                                    <h6>Logo Design</h6>
                                    <p class="m-0">lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
                                </td>
                                <td>5</td>
                                <td>$150.00</td>
                                <td>$750.00</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-responsive invoice-table invoice-total">
                    <tbody>
                    <tr>
                    <th>Sub Total :</th>
                    <td>$4725.00</td>
                    </tr>
                    <tr>
                    <th>Taxes (10%) :</th>
                    <td>$57.00</td>
                    </tr>
                    <tr>
                    <th>Discount (5%) :</th>
                        <td>$45.00</td>
                    </tr>
                        <tr class="text-info">
                            <td>
                                <hr/>
                                <h5 class="text-primary m-r-10">Total :</h5>
                            </td>
                            <td>
                                <hr/>
                                <h5 class="text-primary">$ 4827.00</h5>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <h6>Terms and Condition :</h6>
                <p>lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                </p>
            </div>
        </div>
    </div>
</div>
<div class="row text-center">
    <div class="col-sm-12 invoice-btn-group text-center">
        <button type="button" class="btn btn-primary btn-print-invoice m-b-10">Print</button>
        <button type="button" class="btn btn-secondary m-b-10 ">Cancel</button>
    </div>
</div>

{% endblock body %}

templates/company/upload.html
{% extends '../dashboard/base.html' %}
{% block body %}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h5>File Upload</h5>
            </div>
            <div class="card-body">
                <form action="../assets/plugins/fileupload/js/file-upload.php" class="dropzone">
                    <div class="fallback">
                        <input name="file" type="file" multiple />
                    </div>
                </form>
            <div class="text-center m-t-20">
                <button class="btn btn-primary">Upload Now</button>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}