Batch/urls.py
from django.urls import path
from .admin import prosperity_admin_site
from . import views

app_name = 'batch'

urlpatterns = [
    # post views
    path('',views.all_batches, name='batches'),
    path('drafts/',views.draft_batches, name='drafts'),
    path('codes/', views.get_deduction_codes, name='codes'),
    path('codes/new/',views.deduction_code_registration, name='code_registration'),
    path('send/batch/',views.send_batch, name='send_batch'),
    path('<int:id>/upload_excel/', views.upload_responses, name='upload_excel'),
    path('<int:id>/',views.view_batch, name='view_batch'),
]

ProsperityPartners/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Accounts.urls',namespace='accounts')),
    path('batches/', include('Batch.urls', namespace='batch')),
    path('companies/', include('Company.urls', namespace='company')),
    path('records/', include('Record.urls', namespace='record')),
    path('responses/', include('Response.urls', namespace='response')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
#django-insecure-m0s&i_6&kcp39hv53*g$=64e6#ppb&efdxm!krv!l7_#q%w&a$

templates/deductioncode/add-deduction-code.html
{% extends '../dashboard/base.html' %}
{% block body %}
<div class="page-header1">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-7">
                <div class="page-header-title">
                    <h5 class="m-b-10 m-t-4 m-l-4">Deduction Codes</h5>
                    <p class="m-b-0"></p>
                </div>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb">
                    {% comment %} <li class="breadcrumb-item">
                        <a href="index.html"> <i class="fa fa-home"></i> </a>
                    </li> {% endcomment %}
                    <li class="breadcrumb-item">
                        <button class="btn waves-effect waves-light btn-primary"><i class="icofont icofont-user-alt-3"></i>New Record</button>
                    </li>
                    <li class="breadcrumb-item">
                        <button class="btn waves-effect waves-light btn-success"><i class="icofont icofont-check-circled"></i>Import Bulk Records</button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Page-header end -->
<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">

            <!-- Page body start -->
            <div class="page-body">
                <div class="row">
                    {% comment %} <div class="col-md-1"></div> {% endcomment %}
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Add Deduction Code</h5>
                            </div>
                            <div class="card-block">
                                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                                    <div class="form-group row">
                                        <div class="col-lg-3"></div>
                                        <div class="col-lg-6">
                                            <label class="float-label">Choose Company <span style="color:red;">*</span></label>
                                            {{form.company}}
                                        </div>
                                        <div class="col-lg-3"></div>
                                        <div class="col-lg-3"></div>
                                        <div class="col-lg-6">
                                            <label class="float-label">Choose Currency <span style="color:red;">*</span></label>
                                            {{form.currency}}
                                        </div>
                                        <div class="col-lg-3"></div>
                                    </div>
                                    <div style="text-align:center;">
                                        <button type="submit" class="btn btn-primary waves-effect waves-light">Create Deduction Code</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% comment %} <div class="col-md-1"></div> {% endcomment %}
                </div>
            </div>
            <!-- Page body end -->
        </div>
    </div>
    <!-- Main-body end -->
</div>
{% endblock body %}

templates/deductioncode/deduction-codes.html
{% extends '../dashboard/base.html' %}
{% load static %}

{% block body %}
<div class="page-header1">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-9">
                <div class="page-header-title">
                    <h5 class="m-b-10 m-t-4 m-l-4">Deduction Codes Management</h5>
                    <p class="m-b-0"></p>
                </div>
            </div>
            <div class="col-md-3">
                <ul class="breadcrumb">
                    {% comment %} <li class="breadcrumb-item">
                        <a href="index.html"> <i class="fa fa-home"></i> </a>
                    </li> {% endcomment %}
                    <li class="breadcrumb-item">
                        <a href="{% url 'batch:code_registration' %}" class="btn waves-effect waves-light btn-success"><i class="icofont icofont-check-circled"></i>Add New Deduction Code</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Page-header end -->
<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Hover table card start -->
            <div class="card">
                <div class="card-header">
                    <h5>Deduction Codes</h5>
                    <div class="card-header-right">
                        <ul class="list-unstyled card-option">
                            <li><i class="fa fa fa-wrench open-card-option"></i></li>
                            <li><i class="fa fa-window-maximize full-card"></i></li>
                            <li><i class="fa fa-minus minimize-card"></i></li>
                            <li><i class="fa fa-refresh reload-card"></i></li>
                            <li><i class="fa fa-trash close-card"></i></li>
                        </ul>
                    </div>
                </div>
                <div class="card-block table-border-style">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr style="background-color:#5A72FE;">
                                    <th></th>
                                    <th style="color:white;">Deduction Code</th>
                                    <th style="color:white;">Company</th>
                                    <th style="color:white;">Currency</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for code in codes %}
                                    <tr>
                                        <th scope="row">{{forloop.counter}}</th>
                                        <td>{{code.deduction_code}}</td>
                                        <td>{{code.company.name}}</td>
                                        <td>{{code.currency}}</td>
                                    </tr>
                                {% empty %}
                                    <p>No deduction codes available yet.</p>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Hover table card end -->
        </div>
        <!-- Page body end -->
    </div>
</div>
<!-- Main-body end -->

{% endblock body %}