Accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='auth/auth-signin.html',form_class=LoginForm), name='login'),
    path('profile/',check_company,name='profile'),
    path('acounts/new/',staff_account_creation,name='create_account'),
    path('accounts/',get_company_users,name='view_accounts'),
    path('security-code/<int:batch_id>/',verify_password,name='add_security_code'),
]

Batch/urls.py
from django.urls import path
from .admin import prosperity_admin_site
from . import views

app_name = 'batch'

urlpatterns = [
    # post views
    path('',views.all_batches, name='batches'),
    path('drafts/',views.draft_batches, name='drafts'),
    path('codes/', views.get_deduction_codes, name='codes'),
    path('codes/new/',views.deduction_code_registration, name='code_registration'),
    path('send/batch/',views.send_batch, name='send_batch'),
    path('<int:id>/upload_excel/', views.upload_responses, name='upload_excel'),
    path('<int:id>/',views.view_batch, name='view_batch'),
]

ProsperityPartners/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Accounts.urls',namespace='accounts')),
    path('batches/', include('Batch.urls', namespace='batch')),
    path('companies/', include('Company.urls', namespace='company')),
    path('records/', include('Record.urls', namespace='record')),
    path('responses/', include('Response.urls', namespace='response')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
#django-insecure-m0s&i_6&kcp39hv53*g$=64e6#ppb&efdxm!krv!l7_#q%w&a$

Record/urls.py
from django.urls import path
from . import views

app_name = 'record'

urlpatterns = [
    # post views
    path('', views.get_records, name='records'),
    path('new/',views.record_registration, name='new_record'),
    path('upload/',views.import_data, name='upload'),
    path('<str:record_id>/',views.record_detail, name='record_detail'),
    path('search/',views.filter_type, name='search'),
    path('search/status/',views.filter_status, name='search_status'),
]

Response/urls.py
from django.urls import path
from . import views

app_name = 'response'

urlpatterns = [
    # post views
    path('responses/',views.responses, name='responses'),
    path('response/success/<int:id>/',views.success_responses, name='success_responses'),
    path('response/failed/<int:id>/',views.failed_responses, name='failed_responses'),
]

Batch/forms.py
from django import forms
import re

from Batch.models import DeductionCode


class DeductionCodeForm(forms.ModelForm):
    company = forms.Select()
    currency = forms.Select()
    class Meta:
        model = DeductionCode
        fields = ['company', 'currency']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['company'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})
        self.fields['currency'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})

Record/forms.py
from django import forms
import re

from Record.models import Record


class UploadForm(forms.ModelForm):
    file = forms.FileInput()
    deduction_code = forms.Select()
    class Meta:
        model = Record
        fields = ("deduction_code",)
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['deduction_code'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})
        # self.fields['file'].widget.attrs.update(
        #     {'class': 'form-control form-control-lg'})

class RecordForm(forms.ModelForm):
    deduction_code = forms.Select()
    request_type = forms.Select()
    ec_number = forms.CharField(max_length=8)
    id_number = forms.CharField(max_length=11)
    transaction_refence = forms.CharField(max_length=20)
    deductions_start_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    deductions_end_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    installment_amount = forms.IntegerField()
    class Meta:
        model = Record
        fields = ['deduction_code', 'request_type','ec_number','id_number',
                  'transaction_refence','deductions_start_date',
                  'deductions_end_date','installment_amount']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['deduction_code'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})
        self.fields['request_type'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})
        self.fields['ec_number'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})
        self.fields['id_number'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})
        self.fields['transaction_refence'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})
        self.fields['deductions_start_date'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})
        self.fields['deductions_end_date'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})
        self.fields['installment_amount'].widget.attrs.update(
            {'class': 'form-control form-control-lg'})
        

Response/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField()

Batch/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.db.models import Sum

from openpyxl import load_workbook

# Create your views here.

from Batch.models import Batch, DeductionCode
from Batch.forms import DeductionCodeForm
from Company.models import Company
from Response.models import Response

def deduction_code_registration(request):
    if request.method =='POST':
        form = DeductionCodeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("batch:codes")
    else:
        form = DeductionCodeForm()
    return render(request,'deductioncode/add-deduction-code.html',{'form':form})

# @login_required
def get_deduction_codes(request):
    codes = DeductionCode.objects.all()
    return render(request,'deductioncode/deduction-codes.html',{'codes':codes})


def all_batches(request):
    company_id = request.session.get('company_id')
    company = Company.objects.get(id=company_id)
    batches = company.company_batches.all()
    return render(request,'dashboard/batches.html',{'batches':batches})


def draft_batches(request):
    batches = Batch.draft.all()
    return render(request,'dashboard/drafts.html',{'batches':batches})

def view_batch(request,id):
    batch = get_object_or_404(Batch,id=id)
    total_price = batch.batch_records.aggregate(Sum('installment_amount'))['installment_amount__sum']
    print(total_price)
    #cost = str(float(total_price)/100.00)
    return render(request,'dashboard/batch.html',{'batch':batch,'total_value':str(total_price/100.00)})

def send_batch(request):
    is_one = False
    company_id = request.session.get('company_id')
    company = Company.objects.get(id=company_id)
    batches = company.company_batches.filter(status = Batch.Status.DRAFT)
    if batches.count() == 1:
        is_one = True
    return render(request,'dashboard/drafts.html',{'batches':batches,'is_one':is_one})


# views.py

def upload_excel(request):
    if request.method == 'POST':
        file = request.FILES['excel_file']
        wb = load_workbook(filename=file)
        ws = wb.active
        for row in ws.iter_rows(min_row=2):
            pass
            # data = [cell.value for cell in row]
            # obj = MyModel(field1=data[0], field2=data[1], field3=data[2])
            # obj.save()
        return render(request, 'admin/upload_excel_success.html')
    else:
        return render(request, 'admin/upload_excel_form.html')
    
    
#@login_required
def upload_responses(request,id):
    if request.method == 'POST':
        # Get the uploaded file
        file = request.FILES['excel_file']
        # Open the file using openpyxl
        workbook = load_workbook(filename=file, read_only=True)
        worksheet = workbook.active
        batch = get_object_or_404(Batch,id=id)

        # Loop through the rows and save each record to the database
        for row in worksheet.iter_rows(min_row=2, values_only=True):
            recid = row[0]
            deductionCode = row[1]
            reference = row[2]
            idNumber = row[3]
            ecNumber = row[4]
            type = row[5]
            status = row[6]
            startDate = row[7]
            endDate = row[8]
            amount = row[9]
            name = row[10]
            bankAccount = row[11]
            message = row[12]
            
            #upload record
            Response.objects.create(
                batch=batch,
                recid=recid,
                deductionCode=deductionCode,
                reference = reference,
                idNumber = idNumber,
                ecNumber=ecNumber,
                type = type,
                status = status,
                startDate = startDate,
                endDate = endDate,
                amount = amount,
                name = name,
                bankAccount = bankAccount,
                message = message
            )
        batch.status = Batch.Status.SUCCESS
        batch.save()
            
        # Redirect to a success page
        return render(request, 'admin/upload_excel_success.html')
    else:
        return render(request, 'admin/upload_excel_form.html')
    

    # Render the form if the request method is GET
    codes = DeductionCode.objects.all()
    return render(request, 'dashboard/upload-batch.html', {'codes': codes})

    

Record/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest
import xlrd
from openpyxl import load_workbook
import datetime

from Batch.models import Batch,DeductionCode
from Company.models import Company
from Record.models import Record
from Record.forms import RecordForm,UploadForm


@login_required
def import_data(request):
    if request.method == 'POST':
        # Get the uploaded file
        file = request.FILES['batch_file']
        code = request.POST.get('select')
        # Open the file using openpyxl
        workbook = load_workbook(filename=file, read_only=True)
        worksheet = workbook.active

        #get company instance
        company_id = request.session.get('company_id')
        company = Company.objects.get(id=company_id) 
        # Get the deduction code and create a new batch
        deduction_code = DeductionCode.objects.get(id=int(code))
        new_batch = Batch.objects.create(deduction_code=deduction_code,company=company)

        # Loop through the rows and save each record to the database
        for row in worksheet.iter_rows(min_row=2, values_only=True):
            reference = row[0]
            id_number = row[1]
            ec_number = row[2]
            type = row[3]
            start_date = row[4]
            end_date = row[5]
            # start_date = datetime.datetime.strptime(str(row[4]), '%d-%m-%Y').strftime('%Y-%m-%d')
            # end_date = datetime.datetime.strptime(str(row[5]), '%d-%m-%Y').strftime('%Y-%m-%d')
            amount = row[6]
            if not (reference == None or type == None or ec_number == None):
                Record.objects.create(
                    batch=new_batch,
                    deduction_code=deduction_code,
                    code=deduction_code.code,
                    request_type=type,
                    ec_number=ec_number,
                    id_number=id_number,
                    transaction_refence=reference,
                    deductions_start_date=start_date,
                    deductions_end_date=end_date,
                    installment_amount=amount
                )
        # Redirect to a success page
        return redirect('record:records')

    # Render the form if the request method is GET
    codes = DeductionCode.objects.all()
    return render(request, 'dashboard/upload-batch.html', {'codes': codes})

@login_required
def record_registration(request):
    if request.method =='POST':
        form = RecordForm(request.POST)
        if form.is_valid():
            record = form.save(commit=False)
            #get company instance
            company_id = request.session.get('company_id')
            company = Company.objects.get(id=company_id) 
            batch = Batch.objects.filter(company=company,status = Batch.Status.DRAFT).last()
            if batch:
                record.batch = batch
                record.record_source = "Individual Upload"
                record.save()
            else:
                dd_code =request.POST.get('deduction_code')
                deduction_code = DeductionCode.objects.get(id=dd_code)
                new_batch = Batch.objects.create(deduction_code = deduction_code,company=company)
                record.batch = new_batch
                record.record_source = "Individual Upload"
                record.save()
            return redirect("record:records")
    else:
        form = RecordForm()
    return render(request,'dashboard/add-record.html',{'form':form})

@login_required
def get_records(request):
    company_id = request.session.get('company_id')
    company = Company.objects.get(id=company_id) 
    records = Record.objects.filter(batch__company = company).select_related('batch')
    return render(request,'dashboard/records.html',{'records':records,'company':company})

@login_required
def filter_type(request):
    selected_option = request.GET.get('type')
    # Perform the necessary query based on the selected option
    if selected_option == 'NEW':
        records = Record.objects.filter(request_type='NEW')
    elif selected_option == 'CHANGE':
        records= Record.objects.filter(request_type='CHANGE')
    elif selected_option == 'DELETE':
        records = Record.objects.filter(status='DELETE')
    return render(request,'dashboard/records.html',{'records':records})

@login_required
def filter_status(request):
    selected_option = request.GET.get('type')
    # Perform the necessary query based on the selected option
    if selected_option == 'CANCELED':
        records = Record.objects.filter(status='CANCELED')
    elif selected_option == 'DRAFT':
        records= Record.objects.filter(status='DRAFT')
    elif selected_option == 'FAILED':
        records = Record.objects.filter(status='FAILED')
    elif selected_option == 'PROCESSED':
        records = Record.objects.filter(status='PROCESSED')
    elif selected_option == 'PROCESSING':
        records = Record.objects.filter(status='PROCESSING')
    elif selected_option == 'SUCCESS':
        records = Record.objects.filter(status='SUCCESS')
    elif selected_option == 'SENT':
        records = Record.objects.filter(status='SENT')
    elif selected_option == 'SAVED':
        records = Record.objects.filter(status='SAVED')
        
    return render(request,'dashboard/records.html',{'records':records})
    
@login_required
def record_detail(request, record_id):
    record = Record.objects.get(record_id=record_id)
    return render(request,'dashboard/record.html',{'record':record})

Response/views.py
from django.shortcuts import render
from django.contrib.postgres.search import SearchVector

from Batch.models import Batch
from Company.models import Company
from Response.forms import SearchForm
from Record.models import Record

# Create your views here.


def responses(request):
    company_id = request.session.get('company_id')
    company = Company.objects.get(id=company_id)
    batches = company.company_batches.filter(status = Batch.Status.SUCCESS)
    return render(request,'dashboard/responses.html',{'batches':batches})

def success_responses(request,id):
    batch = Batch.objects.get(id =id)
    responses = batch.responses.filter(status = 'SUCCESS')
    return render(request,'dashboard/response_type.html',{'responses':responses})

def failed_responses(request,id):
    batch = Batch.objects.get(id =id)
    responses = batch.responses.filter(status = 'FAILED')
    return render(request,'dashboard/response_type.html',{'responses':responses})

def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Record.published.annotate(
                search=SearchVector('title', 'body'),).filter(search=query)

    return render(request,'blog/post/search.html',
                  {'form': form,'query': query,'results': results})

templates/dashboard/add-record.html
{% extends './base.html' %}
{% block body %}
<div class="page-header1">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-7">
                <div class="page-header-title">
                    <h5 class="m-b-10 m-t-4 m-l-4">Records Management</h5>
                    <p class="m-b-0"></p>
                </div>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb">
                    {% comment %} <li class="breadcrumb-item">
                        <a href="index.html"> <i class="fa fa-home"></i> </a>
                    </li> {% endcomment %}
                    <li class="breadcrumb-item">
                        <button class="btn waves-effect waves-light btn-primary"><i class="icofont icofont-user-alt-3"></i>New Record</button>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'record:upload' %}" class="btn waves-effect waves-light btn-success"><i class="icofont icofont-check-circled"></i>Import Bulk Records</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Page-header end -->
<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">

            <!-- Page body start -->
            <div class="page-body">
                <div class="row">
                    {% comment %} <div class="col-md-1"></div> {% endcomment %}
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Add New Record</h5>
                            </div>
                            <div class="card-block">
                                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                                    <div class="form-group row">
                                        <div class="col-lg-6">
                                            <label class="float-label">Choose Deduction Code <span style="color:red;">*</span></label>
                                            {{form.deduction_code}}
                                        </div>
                                        <div class="col-lg-6">
                                            <label class="float-label">Choose Request Type<span style="color:red;">*</span></label>
                                            {{form.request_type}}
                                        </div>
                                        <div class="col-lg-6">
                                            <label class="float-label">EC Number<span style="color:red;">*</span></label>
                                            {{form.ec_number}}
                                        </div>
                                        <div class="col-lg-6">
                                            <label class="float-label">National ID Number<span style="color:red;">*</span></label>
                                            {{form.id_number}}
                                        </div>
                                        <div class="col-lg-6">
                                            <label class="float-label">Deduction Start Date<span style="color:red;">*</span></label>
                                            {{form.deductions_start_date}}
                                        </div>
                                        <div class="col-lg-6">
                                            <label class="float-label">Deduction End Date<span style="color:red;">*</span></label>
                                            {{form.deductions_end_date}}
                                        </div>
                                        <div class="col-lg-6">
                                            <label class="float-label">Transaction Reference<span style="color:red;">*</span></label>
                                            {{form.transaction_refence}}
                                        </div>
                                        <div class="col-lg-6">
                                            <label class="float-label">Installment Amount <span style="color:red;"> (cents)</span></label>
                                            {{form.installment_amount}}
                                        </div>
                                        
                                    </div>
                                    <div style="text-align:center;">
                                        <button class="btn btn-primary waves-effect waves-light">Add Record</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% comment %} <div class="col-md-1"></div> {% endcomment %}
                </div>
            </div>
            <!-- Page body end -->
        </div>
    </div>
    <!-- Main-body end -->
</div>
{% endblock body %}

templates/dashboard/records.html
{% extends './base.html' %}
{% load static %}

{% block body %}
<div class="page-header1">
    <div class="row">
        <div class="col">
            <div class="card task-board-left">
                {% comment %} <div class="card-header">
                    <h5>Search Box</h5>
                </div> {% endcomment %}
                <div class="card-body">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control add_task_todo" placeholder="Search here..." required>
                        <div class="input-group-append">
                            <button class="btn btn-primary btn-icon btn-msg-send" type="button"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-2">
                
            </div>
            <div class="col-md-10">
                <ul class="breadcrumb">
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <select name="status" id="type-status" class="form-control">
                                <option value="0" disabled selected>Choose Status</option>
                                <option value="CANCELED">CANCELED</option>
                                <option value="DRAFT">DRAFT</option>
                                <option value="FAILED">FAILED</option>
                                <option value="PROCESSED">PROCESSED</option>
                                <option value="PROCESSING">PROCESSING</option>
                                <option value="SUCCESS">SUCCESS</option>
                                <option value="SENT">SENT</option>
                                <option value="SAVED">SAVED</option>
                            </select>
                        </div>
                        <div class="col-sm-6">
                            <select name="type" class="form-control" id="type-select">
                                <option value="0" selected disabled>Choose Type</option>
                                <option value="NEW">NEW</option>
                                <option value="CHANGE">CHANGE</option>
                                <option value="DELETE">DELETE</option>
                            </select>
                        </div>

                    </div>
                    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;
                    <div class="btn-group " role="group" data-toggle="tooltip" data-placement="top" title="" data-original-title="Choose Option">
                        <a href="#" type="button" class="btn waves-effect waves-light btn-inverse"><i class="icofont icofont-exchange"></i>Download List</a>
                        <a href="{% url 'batch:batches' %}" type="button" class="btn waves-effect waves-light btn-success"><i class="icofont icofont-check-circled"></i>View Batches</a>
                        <a href="{% url 'record:new_record' %}" type="button" class="btn waves-effect waves-light btn-primary"><i class="icofont icofont-user-alt-3"></i>New Record</a>
                    </div>
                    {% comment %} <li class="breadcrumb-item">
                        <a href="#" class="btn waves-effect waves-light btn-success"><i class="icofont icofont-check-circled"></i>View Batches</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'record:new_record' %}" class="btn waves-effect waves-light btn-primary"><i class="icofont icofont-user-alt-3"></i>New Record</a>
                    </li> {% endcomment %}
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Page-header end -->
<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Hover table card start -->
            <div class="card">
                <div class="card-header">
                    <h5>Deduction Requests</h5>
                    <div class="card-header-right">
                        <ul class="list-unstyled card-option">
                            <li><i class="fa fa fa-wrench open-card-option"></i></li>
                            <li><i class="fa fa-window-maximize full-card"></i></li>
                            <li><i class="fa fa-minus minimize-card"></i></li>
                            <li><i class="fa fa-refresh reload-card"></i></li>
                            <li><i class="fa fa-trash close-card"></i></li>
                        </ul>
                    </div>
                </div>
                <div class="card-block table-border-style">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr style="background-color:#5A72FE;">
                                    <th></th>
                                    <th style="color:white;">Record ID</th>
                                    <th style="color:white;">Reference</th>
                                    {% comment %} <th style="color:white;">Code</th> {% endcomment %}
                                    <th style="color:white;">Type</th>
                                    <th style="color:white;">Status</th>
                                    <th style="color:white;">ID Number</th>
                                    <th style="color:white;">EC Number</th>
                                    <th style="color:white;">Amount</th>
                                    <th style="color:white;">Date Created</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for record in records %}
                                    <tr>
                                        <th scope="row">{{forloop.counter}}</th>
                                        <td><a style="color:blue;" href="{% url 'record:record_detail' record.record_id %}">{{record.record_id}}</a></td>
                                        <td>{{record.transaction_refence}}</td>
                                        {% comment %} <td>{{record.code}}</td> {% endcomment %}
                                        <td>{{record.request_type}}</td>
                                        <td><label class="label label-info">{{record.status}}</label></td>
                                        <td>{{record.id_number}}</td>
                                        <td>{{record.ec_number}}</td>
                                        <td>{{record.installment_amount}}</td>
                                        <td>{{record.date_created | timesince}} ago</td>
                                    </tr>
                                {% empty %}
                                    <p>No record available.</p>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Hover table card end -->
        </div>
        <!-- Page body end -->
    </div>
</div>
<!-- Main-body end -->
<script>
    const dropdown = document.querySelector('#type-status');
  
    dropdown.addEventListener('change', (event) => {
      const selectedOption = event.target.value;
      console.log(`Selected option: ${selectedOption}`);
  
      // Redirect the user to the search view with the selected option as a query parameter
      window.location.href = `{% url 'record:search_status' %}?type=${selectedOption}`;
    });

    const dropdown2 = document.querySelector('#type-select');
  
    dropdown2.addEventListener('change', (event) => {
      const selectedOption = event.target.value;
      console.log(`Selected option: ${selectedOption}`);
  
      // Redirect the user to the search view with the selected option as a query parameter
      window.location.href = `{% url 'record:search' %}?type=${selectedOption}`;
    });
  </script>

<script>
    const dropdown = document.querySelector('#type-select');
  
    dropdown.addEventListener('change', (event) => {
      const selectedOption = event.target.value;
      console.log(`Selected option: ${selectedOption}`);
  
      // Redirect the user to the search view with the selected option as a query parameter
      window.location.href = `{% url 'record:search' %}?type=${selectedOption}`;
    });
  </script>


  
  

{% endblock body %}